export { default as GetStarted } from "./GetStarted";
export { default as HomePage } from "./HomePage";
export { default as LeaderBoard } from "./LeaderBoard";
export { default as Account } from "./Account";
export { default as Settings } from "./Settings";
export { default as Gang } from "./Gang";
export { default as Casino } from "./Casino";
export { default as Earn } from "./Earn";
export { default as Meme } from "./Meme";
